// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace PetApiTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Pet API CRUD")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class PetAPICRUDFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Pet API CRUD", "  In order to manage pets in the store\r\n  As an API tester\r\n  I want to create, u" +
                "pdate, get and delete a pet", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "PetApi.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Io.Cucumber.Messages.Types.Source SourceFunc()
        {
            return new global::Io.Cucumber.Messages.Types.Source("Features/PetApi.feature", "Feature: Pet API CRUD\r\n  In order to manage pets in the store\r\n  As an API tester" +
                    "\r\n  I want to create, update, get and delete a pet\r\n\r\n  @crud @pet @smoke\r\n  Sce" +
                    "nario: Happy path CRUD for a single pet\r\n    Given a new pet with id 8073 and na" +
                    "me \"shihtzu\"\r\n    When I send a POST request to create the pet\r\n    Then the res" +
                    "ponse status code should be 200\r\n    And the response should contain pet id 8073" +
                    " and name \"shihtzu\"\r\n\r\n    When I send a PUT request to update the pet name to \"" +
                    "bulldog\"\r\n    Then the response status code should be 200\r\n    And the response " +
                    "should contain pet id 8073 and name \"bulldog\"\r\n\r\n    When I send a GET request t" +
                    "o retrieve the pet by id 8073\r\n    Then the response status code should be 200\r\n" +
                    "    And the response should contain pet id 8073 and name \"bulldog\"\r\n\r\n    When I" +
                    " send a DELETE request to delete the pet with id 8073\r\n    Then the response sta" +
                    "tus code should be 200\r\n    And the delete response should contain pet id 8073\r\n" +
                    "\r\n    When I send a GET request to retrieve the pet by id 8073\r\n    Then the res" +
                    "ponse status code should be 404\r\n    And the response should contain error messa" +
                    "ge \"Pet not found\"\r\n\r\n  @post @pet @smoke\r\n  Scenario: Create pet using POST /pe" +
                    "t and response code should be 200\r\n    Given a new pet with id 8073 and name \"sh" +
                    "ihtzu\"\r\n    When I send a POST request to create the pet\r\n    Then the response " +
                    "status code should be 200\r\n    And the response should contain pet id 8073 and n" +
                    "ame \"shihtzu\"\r\n\r\n  @get @pet @smoke\r\n  Scenario: Get pet using GET /pet/{petid} " +
                    "and response code should be 200\r\n    Given a new pet with id 8073 and name \"shih" +
                    "tzu\"\r\n    When I send a POST request to create the pet\r\n    And I send a GET req" +
                    "uest to retrieve the pet by id 8073\r\n    Then the response status code should be" +
                    " 200\r\n    And the response should contain pet id 8073 and name \"shihtzu\"\r\n\r\n  @d" +
                    "elete @pet @smoke\r\n  Scenario: Delete pet using DELETE /pet/{petid} and response" +
                    " code should be 200\r\n    Given a new pet with id 8073 and name \"shihtzu\"\r\n    Wh" +
                    "en I send a POST request to create the pet\r\n    And I send a DELETE request to d" +
                    "elete the pet with id 8073\r\n    Then the response status code should be 200\r\n   " +
                    " And the delete response should contain pet id 8073\r\n\r\n  @delete @pet @smoke\r\n  " +
                    "Scenario: Delete pet twice using DELETE /pet/{petid} and response code of second" +
                    " delete should be 404\r\n    Given a new pet with id 8073 and name \"shihtzu\"\r\n    " +
                    "When I send a POST request to create the pet\r\n    And I send a DELETE request to" +
                    " delete the pet using the same pet id\r\n    And I send a DELETE request to delete" +
                    " the pet using the same pet id\r\n    Then the response status code should be 404\r" +
                    "\n   \r\n    \r\n  @post @pet @smoke\r\n  Scenario Outline: Create pet using POST /pet " +
                    "and validate the correct response codes\r\n    Given a new pet with id <id> and na" +
                    "me \"<name>\"\r\n    When I send a POST request to create the pet\r\n    Then the resp" +
                    "onse status code should be <expectedStatusCode>\r\n    And the response should con" +
                    "tain pet id <id> and name \"<name>\"\r\n\r\n    Examples:\r\n      | id   | name     | e" +
                    "xpectedStatusCode |\r\n      | 8073 | shihtzu  | 200                |\r\n      | 999" +
                    "9 | poodle   | 200                |\r\n      | 3434 | chowchow | 200              " +
                    "  |\r\n      | 6445 | beagle   | 200                |\r\n      | 2324 | bulldog  | 2" +
                    "00                |\r\n\r\n    \r\n", global::Io.Cucumber.Messages.Types.SourceMediaType.TEXT_X_CUCUMBER_GHERKIN_PLAIN);
        }
        
        private static global::Io.Cucumber.Messages.Types.GherkinDocument GherkinDocumentFunc()
        {
            return new global::Io.Cucumber.Messages.Types.GherkinDocument("Features/PetApi.feature", new global::Io.Cucumber.Messages.Types.Feature(new global::Io.Cucumber.Messages.Types.Location(1, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "en-US", "Feature", "Pet API CRUD", "  In order to manage pets in the store\r\n  As an API tester\r\n  I want to create, u" +
                        "pdate, get and delete a pet", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.FeatureChild>(new global::Io.Cucumber.Messages.Types.FeatureChild[] {
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(7, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(6, new System.Nullable<long>(3)), "@crud", "3595be22302e6d52b397d3698204f82b"),
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(6, new System.Nullable<long>(9)), "@pet", "f84fdd72b91a1953bf6d28bd3f3e47b5"),
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(6, new System.Nullable<long>(14)), "@smoke", "425f8d22a5aad95398b8d0d672e48bfd")}), "Scenario", "Happy path CRUD for a single pet", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(8, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "a new pet with id 8073 and name \"shihtzu\"", null, null, "21cb9e951bc9395e86b666da5e8a3592"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(9, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I send a POST request to create the pet", null, null, "b96bcdb58f000452866ee79e0a969a34"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(10, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the response status code should be 200", null, null, "8ec461b4323cda5295cd8534382342d7"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(11, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the response should contain pet id 8073 and name \"shihtzu\"", null, null, "f5b3bbd4e00d955498ce4d7880f4e419"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(13, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I send a PUT request to update the pet name to \"bulldog\"", null, null, "617c3efb93b94c5884505aa714e7ed3a"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(14, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the response status code should be 200", null, null, "f2084742262ca857954a7ae49c028881"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the response should contain pet id 8073 and name \"bulldog\"", null, null, "56b4eef5a81eb252aa8d8624f545277a"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I send a GET request to retrieve the pet by id 8073", null, null, "bf8ff8756062505a881d447cbccfcefe"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the response status code should be 200", null, null, "d6c5e2902b21cf55b2f1bcad6449a3d3"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the response should contain pet id 8073 and name \"bulldog\"", null, null, "9b94f0b01c1c405b8d9f9a9819ae520e"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I send a DELETE request to delete the pet with id 8073", null, null, "a747904e3b09095d8d6e5a4679c91cbf"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(22, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the response status code should be 200", null, null, "60e5ff54aaf4645bb9e962044688f261"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(23, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the delete response should contain pet id 8073", null, null, "a6752d144135085d8e89bdf15b2f371b"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I send a GET request to retrieve the pet by id 8073", null, null, "d1955eee2211b8589b5ad1a5c90c0124"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(26, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the response status code should be 404", null, null, "011d21f5db8ef454a552372961084df4"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the response should contain error message \"Pet not found\"", null, null, "653fed4582d2745899482af4da374b2e")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "045b5ce3ad1f735dac83f321eeb8fe0c")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(30, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(29, new System.Nullable<long>(3)), "@post", "1ce19e264d945a5295f5e0d046cd902e"),
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(29, new System.Nullable<long>(9)), "@pet", "424af7a73b71c0509cc6d2393cca25d6"),
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(29, new System.Nullable<long>(14)), "@smoke", "bdfceabac363ec5c8cfe8b2eadb8c656")}), "Scenario", "Create pet using POST /pet and response code should be 200", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(31, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "a new pet with id 8073 and name \"shihtzu\"", null, null, "d5904c8ed90d345495afcf8c360e0e71"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(32, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I send a POST request to create the pet", null, null, "1b9e8ba2c946cb549c53348a06081a72"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(33, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the response status code should be 200", null, null, "9342c756374583579e8f3e3b1be39a93"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(34, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the response should contain pet id 8073 and name \"shihtzu\"", null, null, "c3d9fb999db20d52b63b1f38e44bf82f")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "538af38fc7c486519a85e3330705d5ca")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(37, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(36, new System.Nullable<long>(3)), "@get", "444894c92ab79d5ea95acec5d21110c6"),
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(36, new System.Nullable<long>(8)), "@pet", "124a93d414740751a996d58201c8108b"),
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(36, new System.Nullable<long>(13)), "@smoke", "3268454190773c52b3b1ee2c95e1c022")}), "Scenario", "Get pet using GET /pet/{petid} and response code should be 200", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(38, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "a new pet with id 8073 and name \"shihtzu\"", null, null, "1c597f6f19a8e35bb34a2d93b9f045a0"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(39, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I send a POST request to create the pet", null, null, "c70c83910d75d35a8f8423e276e07f50"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(40, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I send a GET request to retrieve the pet by id 8073", null, null, "2a7aecf0b7fb1d548195fde03d34a73a"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(41, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the response status code should be 200", null, null, "7e8d69af7db67a5fb74548319db5ddb9"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(42, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the response should contain pet id 8073 and name \"shihtzu\"", null, null, "e1672038919c735aa23b409dd4a4a9b1")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "dd688f1683ec4154b3c26834c45a2e89")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(45, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(44, new System.Nullable<long>(3)), "@delete", "a68e98361d552c50b028d4d02f990daf"),
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(44, new System.Nullable<long>(11)), "@pet", "f2d9d8e27680d05991ebeab5c7c06624"),
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(44, new System.Nullable<long>(16)), "@smoke", "38b1f91d7357755080598bea99c0abcf")}), "Scenario", "Delete pet using DELETE /pet/{petid} and response code should be 200", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(46, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "a new pet with id 8073 and name \"shihtzu\"", null, null, "9ce7ede9bf879654828092535e25fbbd"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(47, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I send a POST request to create the pet", null, null, "e2abf6cb37a86f54a9187b34cb6e3c17"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(48, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I send a DELETE request to delete the pet with id 8073", null, null, "1f961753f38a465ea5dfc487344ac2e1"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(49, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the response status code should be 200", null, null, "1581a5b8c5ecfa5ba93f724d800b9165"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(50, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the delete response should contain pet id 8073", null, null, "9182d9d6be2f9153a3795f49b4024019")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "fac71868230cd05eb5d78f9ab11c98d1")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(53, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(52, new System.Nullable<long>(3)), "@delete", "5e5c94b62b504b50b924a24ecb42f27f"),
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(52, new System.Nullable<long>(11)), "@pet", "928347bbafd6995ab3b02504a1e7b749"),
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(52, new System.Nullable<long>(16)), "@smoke", "ebd205095773585f93a99a32f05f2619")}), "Scenario", "Delete pet twice using DELETE /pet/{petid} and response code of second delete sho" +
                                            "uld be 404", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(54, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "a new pet with id 8073 and name \"shihtzu\"", null, null, "2b628210c98e4553a0f1b84ee47b38c3"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(55, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I send a POST request to create the pet", null, null, "02463bd7f60a805c8779df3b4a55deed"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(56, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I send a DELETE request to delete the pet using the same pet id", null, null, "deeb67a0ddf3b85b97c2d82a60b4d0cc"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(57, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I send a DELETE request to delete the pet using the same pet id", null, null, "ffb7e0735984b05295183453a4d57852"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(58, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the response status code should be 404", null, null, "644f115d7e66315a9bec85e8823d6443")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "78f1cf80a9130d5898a58fc14035f800")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(62, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(61, new System.Nullable<long>(3)), "@post", "74b9a76705c5bb5b96f11fedbd2e522d"),
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(61, new System.Nullable<long>(9)), "@pet", "3c6c130458353457803f42cffb92a3bb"),
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(61, new System.Nullable<long>(14)), "@smoke", "cce7c3083721f250a50429ae99f74b2c")}), "Scenario Outline", "Create pet using POST /pet and validate the correct response codes", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(63, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "a new pet with id <id> and name \"<name>\"", null, null, "e4cd9f7ca1fc0b539f8a4e713420c8cb"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(64, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I send a POST request to create the pet", null, null, "d1cca6b5cb0d8e5ab1b709e610279a50"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(65, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the response status code should be <expectedStatusCode>", null, null, "a56e246f996f6a5799de17e772bc42c4"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(66, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the response should contain pet id <id> and name \"<name>\"", null, null, "e521f55b55ff105796fa2ff284f7518f")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[] {
                                                    new global::Io.Cucumber.Messages.Types.Examples(new global::Io.Cucumber.Messages.Types.Location(68, new System.Nullable<long>(5)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Examples", "", "", new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(69, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(69, new System.Nullable<long>(9)), "id"),
                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(69, new System.Nullable<long>(16)), "name"),
                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(69, new System.Nullable<long>(27)), "expectedStatusCode")}), "718422c109e54752acc0e26b7502e20f"), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableRow>(new global::Io.Cucumber.Messages.Types.TableRow[] {
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(70, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(70, new System.Nullable<long>(9)), "8073"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(70, new System.Nullable<long>(16)), "shihtzu"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(70, new System.Nullable<long>(27)), "200")}), "563795635a087d5c89e31096a73e2f6d"),
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(71, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(71, new System.Nullable<long>(9)), "9999"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(71, new System.Nullable<long>(16)), "poodle"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(71, new System.Nullable<long>(27)), "200")}), "39490a78ab60035092f4241a27ab915b"),
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(72, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(72, new System.Nullable<long>(9)), "3434"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(72, new System.Nullable<long>(16)), "chowchow"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(72, new System.Nullable<long>(27)), "200")}), "97897b9dee808a5e87b6b104bdedb812"),
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(73, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(73, new System.Nullable<long>(9)), "6445"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(73, new System.Nullable<long>(16)), "beagle"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(73, new System.Nullable<long>(27)), "200")}), "734eb3813b0c0458911cdffe92aca54e"),
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(74, new System.Nullable<long>(7)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(74, new System.Nullable<long>(9)), "2324"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(74, new System.Nullable<long>(16)), "bulldog"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(74, new System.Nullable<long>(27)), "200")}), "57817bb2b4060155814126399ac9b3f5")}), "aa4d8b6cb7b50d56911b38acd4e85be8")}), "d27fbf000dae66539b5ea43f47eb4859"))})), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Comment>(new global::Io.Cucumber.Messages.Types.Comment[0]));
        }
        
        private static global::System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle> PicklesFunc()
        {
            return new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Pickle>(new global::Io.Cucumber.Messages.Types.Pickle[] {
                        new global::Io.Cucumber.Messages.Types.Pickle("082c608e5f7fb753ae19dee80aa14d9a", "Features/PetApi.feature", "Happy path CRUD for a single pet", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "21cb9e951bc9395e86b666da5e8a3592"}), "f92826e19da8be539587451db587c3f3", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a new pet with id 8073 and name \"shihtzu\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "b96bcdb58f000452866ee79e0a969a34"}), "52b1fd3a83df615297f4b10770001b4d", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I send a POST request to create the pet"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "8ec461b4323cda5295cd8534382342d7"}), "dd531f0509dd395b955105c8e1196182", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response status code should be 200"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "f5b3bbd4e00d955498ce4d7880f4e419"}), "6ca2be4a18d833538f65d6d6e2a6474d", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response should contain pet id 8073 and name \"shihtzu\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "617c3efb93b94c5884505aa714e7ed3a"}), "31c46acb4c6b5059aacdf0ff16b24bf5", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I send a PUT request to update the pet name to \"bulldog\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "f2084742262ca857954a7ae49c028881"}), "1c8b6d298a37eb508e03b63e21bf3be8", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response status code should be 200"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "56b4eef5a81eb252aa8d8624f545277a"}), "9d6f10def7948159898e0b2a3a7fad2f", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response should contain pet id 8073 and name \"bulldog\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "bf8ff8756062505a881d447cbccfcefe"}), "99949096df49fb5a94c43e3a2516cc54", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I send a GET request to retrieve the pet by id 8073"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "d6c5e2902b21cf55b2f1bcad6449a3d3"}), "3103c7ea2d9e745883e736f0f5ef5c50", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response status code should be 200"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "9b94f0b01c1c405b8d9f9a9819ae520e"}), "81970a275dced35788444f2581cf8467", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response should contain pet id 8073 and name \"bulldog\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a747904e3b09095d8d6e5a4679c91cbf"}), "adb7dff89734b05192e7f19dcb840b8f", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I send a DELETE request to delete the pet with id 8073"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "60e5ff54aaf4645bb9e962044688f261"}), "5576722db6710256a32ce34c6bbbecd6", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response status code should be 200"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a6752d144135085d8e89bdf15b2f371b"}), "1af27a315859dd538993f6d43d636db9", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the delete response should contain pet id 8073"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "d1955eee2211b8589b5ad1a5c90c0124"}), "d157b5fafab08b5fafe46795d47f2f7e", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I send a GET request to retrieve the pet by id 8073"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "011d21f5db8ef454a552372961084df4"}), "b62db761df5c37598303c01d4911b235", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response status code should be 404"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "653fed4582d2745899482af4da374b2e"}), "3f659d953e01625b89a122a893cd03b7", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response should contain error message \"Pet not found\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@crud", "3595be22302e6d52b397d3698204f82b"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@pet", "f84fdd72b91a1953bf6d28bd3f3e47b5"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@smoke", "425f8d22a5aad95398b8d0d672e48bfd")}), new System.Collections.Generic.List<string>(new string[] {
                                        "045b5ce3ad1f735dac83f321eeb8fe0c"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("7f2f697d030fdf59871f364f71f87999", "Features/PetApi.feature", "Create pet using POST /pet and response code should be 200", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "d5904c8ed90d345495afcf8c360e0e71"}), "f4141d594efe7e5ca51292236a7546ee", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a new pet with id 8073 and name \"shihtzu\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "1b9e8ba2c946cb549c53348a06081a72"}), "287b4f5233f57750bbc649f6bff94dc2", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I send a POST request to create the pet"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "9342c756374583579e8f3e3b1be39a93"}), "4a46145c786100579979033395ff1ab3", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response status code should be 200"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c3d9fb999db20d52b63b1f38e44bf82f"}), "caa15a90de92dc5f8083b073d2ac5035", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response should contain pet id 8073 and name \"shihtzu\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@post", "1ce19e264d945a5295f5e0d046cd902e"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@pet", "424af7a73b71c0509cc6d2393cca25d6"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@smoke", "bdfceabac363ec5c8cfe8b2eadb8c656")}), new System.Collections.Generic.List<string>(new string[] {
                                        "538af38fc7c486519a85e3330705d5ca"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("b9d225d289afbf5c9f3f3ae2450815b5", "Features/PetApi.feature", "Get pet using GET /pet/{petid} and response code should be 200", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "1c597f6f19a8e35bb34a2d93b9f045a0"}), "b55ebd27c075975094ee662f90dd7337", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a new pet with id 8073 and name \"shihtzu\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c70c83910d75d35a8f8423e276e07f50"}), "c957bd1977d9905ca277674bc8c3f259", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I send a POST request to create the pet"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "2a7aecf0b7fb1d548195fde03d34a73a"}), "c870db931dc05e5dbff53e9c073ad7b2", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I send a GET request to retrieve the pet by id 8073"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "7e8d69af7db67a5fb74548319db5ddb9"}), "38eeff03c9fdd75e82d60863af95df71", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response status code should be 200"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e1672038919c735aa23b409dd4a4a9b1"}), "4fb0124701ab0b5b8e3f05a30f47db4c", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response should contain pet id 8073 and name \"shihtzu\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@get", "444894c92ab79d5ea95acec5d21110c6"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@pet", "124a93d414740751a996d58201c8108b"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@smoke", "3268454190773c52b3b1ee2c95e1c022")}), new System.Collections.Generic.List<string>(new string[] {
                                        "dd688f1683ec4154b3c26834c45a2e89"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("6c435b7465d9335bb0cb3bcc99d598e5", "Features/PetApi.feature", "Delete pet using DELETE /pet/{petid} and response code should be 200", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "9ce7ede9bf879654828092535e25fbbd"}), "8a5c7328d6d20b5d94d029dbe862fb57", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a new pet with id 8073 and name \"shihtzu\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e2abf6cb37a86f54a9187b34cb6e3c17"}), "72e1062af0774a52984d24f53675864b", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I send a POST request to create the pet"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "1f961753f38a465ea5dfc487344ac2e1"}), "8848f6b1b2f1d359813ca3dd0ed820d5", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I send a DELETE request to delete the pet with id 8073"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "1581a5b8c5ecfa5ba93f724d800b9165"}), "f432d7618250475989fea2f5ed82b0b4", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response status code should be 200"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "9182d9d6be2f9153a3795f49b4024019"}), "0d37e8140436365e9853517f26996fa2", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the delete response should contain pet id 8073")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@delete", "a68e98361d552c50b028d4d02f990daf"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@pet", "f2d9d8e27680d05991ebeab5c7c06624"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@smoke", "38b1f91d7357755080598bea99c0abcf")}), new System.Collections.Generic.List<string>(new string[] {
                                        "fac71868230cd05eb5d78f9ab11c98d1"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("d89c8cf3ee5d69588553838220dfdca1", "Features/PetApi.feature", "Delete pet twice using DELETE /pet/{petid} and response code of second delete sho" +
                                "uld be 404", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "2b628210c98e4553a0f1b84ee47b38c3"}), "84bba14525ba0550ad1e0bddf9405503", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a new pet with id 8073 and name \"shihtzu\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "02463bd7f60a805c8779df3b4a55deed"}), "767451adf84ff95a864aaf4047a37015", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I send a POST request to create the pet"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "deeb67a0ddf3b85b97c2d82a60b4d0cc"}), "80ff2ef9382e1055981ed2fc26b5155c", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I send a DELETE request to delete the pet using the same pet id"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "ffb7e0735984b05295183453a4d57852"}), "939de61e66eccb5b880883d6820355a7", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I send a DELETE request to delete the pet using the same pet id"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "644f115d7e66315a9bec85e8823d6443"}), "b7cda47cda7010518f7a29d7e6120503", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response status code should be 404")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@delete", "5e5c94b62b504b50b924a24ecb42f27f"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@pet", "928347bbafd6995ab3b02504a1e7b749"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@smoke", "ebd205095773585f93a99a32f05f2619")}), new System.Collections.Generic.List<string>(new string[] {
                                        "78f1cf80a9130d5898a58fc14035f800"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("205926c97ff04952a629bb2480c8f2fa", "Features/PetApi.feature", "Create pet using POST /pet and validate the correct response codes", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e4cd9f7ca1fc0b539f8a4e713420c8cb",
                                                        "563795635a087d5c89e31096a73e2f6d"}), "b3664ff7e1f74d52aa9fc6c17d8b302d", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a new pet with id 8073 and name \"shihtzu\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "d1cca6b5cb0d8e5ab1b709e610279a50",
                                                        "563795635a087d5c89e31096a73e2f6d"}), "621a9a110030ac5c8efe159f49277e3e", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I send a POST request to create the pet"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a56e246f996f6a5799de17e772bc42c4",
                                                        "563795635a087d5c89e31096a73e2f6d"}), "4ebf7c797be25e5bb7153bc2e2fb2bba", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response status code should be 200"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e521f55b55ff105796fa2ff284f7518f",
                                                        "563795635a087d5c89e31096a73e2f6d"}), "30ef84eee1275359b355d2a72668912f", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response should contain pet id 8073 and name \"shihtzu\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@post", "74b9a76705c5bb5b96f11fedbd2e522d"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@pet", "3c6c130458353457803f42cffb92a3bb"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@smoke", "cce7c3083721f250a50429ae99f74b2c")}), new System.Collections.Generic.List<string>(new string[] {
                                        "d27fbf000dae66539b5ea43f47eb4859",
                                        "563795635a087d5c89e31096a73e2f6d"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("38021ff2582f6951b25c7fd62b1b9e4e", "Features/PetApi.feature", "Create pet using POST /pet and validate the correct response codes", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e4cd9f7ca1fc0b539f8a4e713420c8cb",
                                                        "39490a78ab60035092f4241a27ab915b"}), "0e874776f1aba75384d8ec28a1fc4a96", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a new pet with id 9999 and name \"poodle\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "d1cca6b5cb0d8e5ab1b709e610279a50",
                                                        "39490a78ab60035092f4241a27ab915b"}), "fee10b5e4110545ead4341a19d8b036a", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I send a POST request to create the pet"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a56e246f996f6a5799de17e772bc42c4",
                                                        "39490a78ab60035092f4241a27ab915b"}), "c0ba83caf4377652a4f56dff56f99afd", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response status code should be 200"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e521f55b55ff105796fa2ff284f7518f",
                                                        "39490a78ab60035092f4241a27ab915b"}), "36f5fe75828eb559862603ac8e69b173", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response should contain pet id 9999 and name \"poodle\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@post", "74b9a76705c5bb5b96f11fedbd2e522d"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@pet", "3c6c130458353457803f42cffb92a3bb"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@smoke", "cce7c3083721f250a50429ae99f74b2c")}), new System.Collections.Generic.List<string>(new string[] {
                                        "d27fbf000dae66539b5ea43f47eb4859",
                                        "39490a78ab60035092f4241a27ab915b"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("69825f1c22edfd5f924bcee9ccdaf9e2", "Features/PetApi.feature", "Create pet using POST /pet and validate the correct response codes", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e4cd9f7ca1fc0b539f8a4e713420c8cb",
                                                        "97897b9dee808a5e87b6b104bdedb812"}), "1d7d9ed2c359d25dbde755ac26474e8d", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a new pet with id 3434 and name \"chowchow\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "d1cca6b5cb0d8e5ab1b709e610279a50",
                                                        "97897b9dee808a5e87b6b104bdedb812"}), "7d80687408d58656b187bea72006c9cb", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I send a POST request to create the pet"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a56e246f996f6a5799de17e772bc42c4",
                                                        "97897b9dee808a5e87b6b104bdedb812"}), "12a029cb2189645ea065de07253aee52", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response status code should be 200"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e521f55b55ff105796fa2ff284f7518f",
                                                        "97897b9dee808a5e87b6b104bdedb812"}), "f1c996b01ea94e50908e5e8bcf467a1b", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response should contain pet id 3434 and name \"chowchow\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@post", "74b9a76705c5bb5b96f11fedbd2e522d"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@pet", "3c6c130458353457803f42cffb92a3bb"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@smoke", "cce7c3083721f250a50429ae99f74b2c")}), new System.Collections.Generic.List<string>(new string[] {
                                        "d27fbf000dae66539b5ea43f47eb4859",
                                        "97897b9dee808a5e87b6b104bdedb812"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("e0a2bf3afb62b253bcd42e8389b7126d", "Features/PetApi.feature", "Create pet using POST /pet and validate the correct response codes", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e4cd9f7ca1fc0b539f8a4e713420c8cb",
                                                        "734eb3813b0c0458911cdffe92aca54e"}), "cb4e0d364db7145b983b2cafe21e51a6", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a new pet with id 6445 and name \"beagle\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "d1cca6b5cb0d8e5ab1b709e610279a50",
                                                        "734eb3813b0c0458911cdffe92aca54e"}), "354c64ede0a9d959afaeefb9fe764650", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I send a POST request to create the pet"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a56e246f996f6a5799de17e772bc42c4",
                                                        "734eb3813b0c0458911cdffe92aca54e"}), "8016cc075503355995b792bad0ccb469", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response status code should be 200"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e521f55b55ff105796fa2ff284f7518f",
                                                        "734eb3813b0c0458911cdffe92aca54e"}), "21591522fc02ed508dacd1349a9eadf4", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response should contain pet id 6445 and name \"beagle\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@post", "74b9a76705c5bb5b96f11fedbd2e522d"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@pet", "3c6c130458353457803f42cffb92a3bb"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@smoke", "cce7c3083721f250a50429ae99f74b2c")}), new System.Collections.Generic.List<string>(new string[] {
                                        "d27fbf000dae66539b5ea43f47eb4859",
                                        "734eb3813b0c0458911cdffe92aca54e"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("0476b72ff27bae55b7fc50bccaf13800", "Features/PetApi.feature", "Create pet using POST /pet and validate the correct response codes", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e4cd9f7ca1fc0b539f8a4e713420c8cb",
                                                        "57817bb2b4060155814126399ac9b3f5"}), "bf086918be3e7f58a353f24ef15660c8", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a new pet with id 2324 and name \"bulldog\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "d1cca6b5cb0d8e5ab1b709e610279a50",
                                                        "57817bb2b4060155814126399ac9b3f5"}), "066c13ae983e6956bd2fe0644ad6196a", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I send a POST request to create the pet"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a56e246f996f6a5799de17e772bc42c4",
                                                        "57817bb2b4060155814126399ac9b3f5"}), "9f7c91fd9c6e705f9974f6fd8f399a61", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response status code should be 200"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e521f55b55ff105796fa2ff284f7518f",
                                                        "57817bb2b4060155814126399ac9b3f5"}), "2c0a2e034e8797569b82f62765a8597c", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response should contain pet id 2324 and name \"bulldog\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@post", "74b9a76705c5bb5b96f11fedbd2e522d"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@pet", "3c6c130458353457803f42cffb92a3bb"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@smoke", "cce7c3083721f250a50429ae99f74b2c")}), new System.Collections.Generic.List<string>(new string[] {
                                        "d27fbf000dae66539b5ea43f47eb4859",
                                        "57817bb2b4060155814126399ac9b3f5"}))});
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages(new global::System.Func<Io.Cucumber.Messages.Types.Source>(PetAPICRUDFeature.SourceFunc), new global::System.Func<Io.Cucumber.Messages.Types.GherkinDocument>(PetAPICRUDFeature.GherkinDocumentFunc), new global::System.Func<System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle>>(PetAPICRUDFeature.PicklesFunc));
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Happy path CRUD for a single pet")]
        [global::NUnit.Framework.CategoryAttribute("crud")]
        [global::NUnit.Framework.CategoryAttribute("pet")]
        [global::NUnit.Framework.CategoryAttribute("smoke")]
        public async global::System.Threading.Tasks.Task HappyPathCRUDForASinglePet()
        {
            string[] tagsOfScenario = new string[] {
                    "crud",
                    "pet",
                    "smoke"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Happy path CRUD for a single pet", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 7
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await testRunner.GivenAsync("a new pet with id 8073 and name \"shihtzu\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 9
    await testRunner.WhenAsync("I send a POST request to create the pet", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 10
    await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 11
    await testRunner.AndAsync("the response should contain pet id 8073 and name \"shihtzu\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 13
    await testRunner.WhenAsync("I send a PUT request to update the pet name to \"bulldog\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 14
    await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 15
    await testRunner.AndAsync("the response should contain pet id 8073 and name \"bulldog\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 17
    await testRunner.WhenAsync("I send a GET request to retrieve the pet by id 8073", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 18
    await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 19
    await testRunner.AndAsync("the response should contain pet id 8073 and name \"bulldog\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
    await testRunner.WhenAsync("I send a DELETE request to delete the pet with id 8073", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 22
    await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 23
    await testRunner.AndAsync("the delete response should contain pet id 8073", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 25
    await testRunner.WhenAsync("I send a GET request to retrieve the pet by id 8073", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 26
    await testRunner.ThenAsync("the response status code should be 404", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 27
    await testRunner.AndAsync("the response should contain error message \"Pet not found\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Create pet using POST /pet and response code should be 200")]
        [global::NUnit.Framework.CategoryAttribute("post")]
        [global::NUnit.Framework.CategoryAttribute("pet")]
        [global::NUnit.Framework.CategoryAttribute("smoke")]
        public async global::System.Threading.Tasks.Task CreatePetUsingPOSTPetAndResponseCodeShouldBe200()
        {
            string[] tagsOfScenario = new string[] {
                    "post",
                    "pet",
                    "smoke"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Create pet using POST /pet and response code should be 200", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 30
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 31
    await testRunner.GivenAsync("a new pet with id 8073 and name \"shihtzu\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 32
    await testRunner.WhenAsync("I send a POST request to create the pet", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 33
    await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 34
    await testRunner.AndAsync("the response should contain pet id 8073 and name \"shihtzu\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Get pet using GET /pet/{petid} and response code should be 200")]
        [global::NUnit.Framework.CategoryAttribute("get")]
        [global::NUnit.Framework.CategoryAttribute("pet")]
        [global::NUnit.Framework.CategoryAttribute("smoke")]
        public async global::System.Threading.Tasks.Task GetPetUsingGETPetPetidAndResponseCodeShouldBe200()
        {
            string[] tagsOfScenario = new string[] {
                    "get",
                    "pet",
                    "smoke"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Get pet using GET /pet/{petid} and response code should be 200", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 37
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 38
    await testRunner.GivenAsync("a new pet with id 8073 and name \"shihtzu\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 39
    await testRunner.WhenAsync("I send a POST request to create the pet", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 40
    await testRunner.AndAsync("I send a GET request to retrieve the pet by id 8073", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 41
    await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 42
    await testRunner.AndAsync("the response should contain pet id 8073 and name \"shihtzu\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Delete pet using DELETE /pet/{petid} and response code should be 200")]
        [global::NUnit.Framework.CategoryAttribute("delete")]
        [global::NUnit.Framework.CategoryAttribute("pet")]
        [global::NUnit.Framework.CategoryAttribute("smoke")]
        public async global::System.Threading.Tasks.Task DeletePetUsingDELETEPetPetidAndResponseCodeShouldBe200()
        {
            string[] tagsOfScenario = new string[] {
                    "delete",
                    "pet",
                    "smoke"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Delete pet using DELETE /pet/{petid} and response code should be 200", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 45
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 46
    await testRunner.GivenAsync("a new pet with id 8073 and name \"shihtzu\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 47
    await testRunner.WhenAsync("I send a POST request to create the pet", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 48
    await testRunner.AndAsync("I send a DELETE request to delete the pet with id 8073", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 49
    await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 50
    await testRunner.AndAsync("the delete response should contain pet id 8073", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Delete pet twice using DELETE /pet/{petid} and response code of second delete sho" +
            "uld be 404")]
        [global::NUnit.Framework.CategoryAttribute("delete")]
        [global::NUnit.Framework.CategoryAttribute("pet")]
        [global::NUnit.Framework.CategoryAttribute("smoke")]
        public async global::System.Threading.Tasks.Task DeletePetTwiceUsingDELETEPetPetidAndResponseCodeOfSecondDeleteShouldBe404()
        {
            string[] tagsOfScenario = new string[] {
                    "delete",
                    "pet",
                    "smoke"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Delete pet twice using DELETE /pet/{petid} and response code of second delete sho" +
                    "uld be 404", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 53
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 54
    await testRunner.GivenAsync("a new pet with id 8073 and name \"shihtzu\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 55
    await testRunner.WhenAsync("I send a POST request to create the pet", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 56
    await testRunner.AndAsync("I send a DELETE request to delete the pet using the same pet id", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 57
    await testRunner.AndAsync("I send a DELETE request to delete the pet using the same pet id", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 58
    await testRunner.ThenAsync("the response status code should be 404", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Create pet using POST /pet and validate the correct response codes")]
        [global::NUnit.Framework.CategoryAttribute("post")]
        [global::NUnit.Framework.CategoryAttribute("pet")]
        [global::NUnit.Framework.CategoryAttribute("smoke")]
        [global::NUnit.Framework.TestCaseAttribute("8073", "shihtzu", "200", "5", null)]
        [global::NUnit.Framework.TestCaseAttribute("9999", "poodle", "200", "6", null)]
        [global::NUnit.Framework.TestCaseAttribute("3434", "chowchow", "200", "7", null)]
        [global::NUnit.Framework.TestCaseAttribute("6445", "beagle", "200", "8", null)]
        [global::NUnit.Framework.TestCaseAttribute("2324", "bulldog", "200", "9", null)]
        public async global::System.Threading.Tasks.Task CreatePetUsingPOSTPetAndValidateTheCorrectResponseCodes(string id, string name, string expectedStatusCode, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "post",
                    "pet",
                    "smoke"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("id", id);
            argumentsOfScenario.Add("name", name);
            argumentsOfScenario.Add("expectedStatusCode", expectedStatusCode);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Create pet using POST /pet and validate the correct response codes", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 62
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 63
    await testRunner.GivenAsync(string.Format("a new pet with id {0} and name \"{1}\"", id, name), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 64
    await testRunner.WhenAsync("I send a POST request to create the pet", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 65
    await testRunner.ThenAsync(string.Format("the response status code should be {0}", expectedStatusCode), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 66
    await testRunner.AndAsync(string.Format("the response should contain pet id {0} and name \"{1}\"", id, name), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
